repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

templates: 
  default: &default
    namespace: backbone
    missingFileHandler: Warn

environments:
  default:
    values:
      - ../environments/env.yaml
      - ../environments/env-secrets.yaml
  lts:
    values:
      - ../environments/naljal-lts.yaml
      - ../environments/naljal-lts-secrets.yaml
  dev:
    values:
      - ../environments/env.yaml
      - ../environments/env-secrets.yaml

releases:
  - name: cert-manager
    chart: ./cert-manager
    namespace: egov
    installed: false
    version: v1.13.3
    disableValidation: true
    values:
      - ./cert-manager/values.yaml
      - {{ toYaml .Values | nindent 8 }}

  - name: minio
    installed: false
    chart: ./minio
    version: 13.3.1
    <<: *default
    values:
      - ./minio/values.yaml
      - {{ toYaml .Values | nindent 8 }}

  - name: postgresql
    installed: false
    chart: ./postgresql
    version: 11.9.13
    <<: *default
    values:
      - ./postgresql/values.yaml
      - {{ toYaml .Values | nindent 8 }}
      - global:
          postgresql:
            auth:
              postgresPassword: {{ .Values.secrets.db.password | quote }}

  - name: redis
    installed: false
    chart: ./redis
    version: 7.2.4
    <<: *default
    values:
      - ./redis/values.yaml
      - {{ toYaml .Values | nindent 8 }}

  - name: elasticsearch
    installed: false
    chart: ./elasticsearch
    version: 8.11.3
    <<: *default
    values:
      - ./elasticsearch/values.yaml
      - {{ toYaml .Values | nindent 8 }}
      - secret:
          password: {{ .Values.secrets.elasticsearch.password }}

  - name: elasticsearch-data
    installed: false
    chart: ./elasticsearch-data
    version: 8.11.3
    <<: *default
    values:
      - ./elasticsearch-data/values.yaml
      - {{ toYaml .Values | nindent 8 }}

  - name: kibana
    installed: false
    chart: ./kibana
    version: 8.11.3
    force: true
    <<: *default
    values:
      - ./kibana/values.yaml
      - {{ toYaml .Values | nindent 8 }}
      - ingress:
          hosts:
            - host: {{ .Values.global.domain }}
              paths:
                - path: /kibana
          tls:
            - secretName: {{ .Values.global.domain }}-tls-certs
              hosts:
                - {{ .Values.global.domain }}

  - name: kafka-kraft
    installed: true
    chart: ./kafka-kraft
    version: 28.2.0
    <<: *default
    values:
      - ./kafka-kraft/values.yaml
      - {{ toYaml .Values | nindent 8 }}
    set:
      - name: kraft.clusterId
        value: {{ .Values.secrets.kafka.clusterID }}

  - name: ingress-nginx
    installed: false
    chart: ./ingress-nginx
    version: 4.10.0
    <<: *default
    values:
      - ./ingress-nginx/values.yaml
      - {{ toYaml .Values | nindent 8 }}
      - domain: {{ .Values.global.domain }}

  - name: playground
    installed: true
    chart: ./playground
    version: 0.1.0
    <<: *default
    values:
      - ./playground/values.yaml
      - {{ toYaml .Values | nindent 8 }}
