{{- with index .Values "secrets" "db" }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "secrets" "db" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "secrets" "db" "username" | b64enc | quote }}
  password: {{ index $.Values "secrets" "db" "password" | b64enc | quote }}
  read-username: {{ index $.Values "secrets" "db" "read_username" | b64enc | quote }}
  read-password: {{ index $.Values "secrets" "db" "read_password" | b64enc | quote }}
  flyway-username: {{ index $.Values "secrets" "db" "flywayUsername" | b64enc | quote }}
  flyway-password: {{ index $.Values "secrets" "db" "flywayPassword" | b64enc | quote }}
{{- end }}
{{- end }}
