{{- with index .Values "secrets" "egov-filestore" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  awskey: {{ .aws_key | b64enc | quote }}
  awssecretkey: {{ .aws_secret_key | b64enc | quote }}
{{- end }}