# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: naljal-uat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'
        - path_regex: naljal-lts\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'
        - path_regex: gujarat\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'          
        - path_regex: karnataka\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'
        - path_regex: assam\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'
        - path_regex: ci\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'
        - path_regex: madhyapradesh\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:432205181273:key/2be701ce-4737-4fae-92ef-e04258a9477d'